### ISSUE TITLE
Please communicate breaking changes more clearly/visible (introduced with 2.0.3)

### ISSUE THREAD

**Issue by aroyarexs** [Futurae-Technologies/android-sdk#1]
Hello

with [version 2.0.3](https://github.com/Futurae-Technologies/android-sdk/releases/tag/v2.0.3) you changed the `ApproveSession.timeout` -> _Remove ApproveSession.timeout internal adjustment to millis_
I guess you follow [Semantic Versioning](https://semver.org) regarding your version name?
So please either follow the semantic versioning or communicate it more clearly/visible as breaking change.
For example, nothing is mentioned in the Migration Guide either.

I also recommend renaming the property to better reflect the unit of the timestamp e.g. `expiresAtEpochSeconds` or `timeoutAsEpochSeconds`.

Regards

Aaron

**Comment by dimitrisFuturae** [comment]
Thank you for opening a well described issue on our Issue tracker. 

You make valid points. We discovered a bug where `ApproveSession.timeout` returned the value in milliseconds while the `SessionInfo.timeout` value was in seconds. Based on that we changed the `ApproveSession.timeout` value to seconds for consistency purposes, and this change was considered to be a bug fix.

We agree with you that this shouldn't have been the case, and that this change should have been considered a Major version as it affects apps that integrate our Mobile SDK, furthermore the change impact was not visible enough, as it was only described on the [release changelog](https://github.com/Futurae-Technologies/android-sdk/releases/tag/v2.0.3).
 
We will refrain from such changes in the future and make sure we are more diligent with following semantic versioning.

Please stay tuned to our [announcements](https://support.futurae.com/hc/en-us/sections/360005707634-Announcements) page, where relevant changes concerning Futurae products will be published, and make sure that you follow it (click follow button) if you would like to be notified about any upcoming news concerning.
