### ISSUE TITLE
New error when trying to activateBiometrics / unlockWithBiometrics after migrating to SDK 3.0.5

### ISSUE THREAD

**Issue by Star-Lord-MSA** [Futurae-Technologies/android-sdk#11]
Hello,

I just updated to Futurae SDK 3.0.5 and now I'm noticing that the methods **activateBiometrics** and **unlockWithBiometrics** are not very reliable. Sometimes I get the following error:

`java.lang.IllegalStateException: Must be called from main thread of fragment host`

but the method is actually called from the UI thread. And also we already provide you the FragmentActivity as parameter, so why do you have this check in place?

The same logic, also fails with:

`com.futurae.sdk.public_api.exception.FTKeystoreOperationException: Decryption failed`

And sometimes it works just fine (without any additional change).

For me there is some kind of race condition on your side, could you please check?

**Comment by dimitrisFuturae** [comment]
Hello and thanks for opening this issue. We have confirmed that SDK operations that use OS authentication (such as `activateBiometrics` or `unlockWithBiometrics`) have a bug in their threading usage when used via the callbacks API. We are planning to release v3.1.0-beta soon that contains a fix for this. We will update the thread when the release is public.

About the occurance of `com.futurae.sdk.public_api.exception.FTKeystoreOperationException: Decryption failed`. This indicates a failure of accessing the appropriate keystore entry for an SDK operation. Could you please provide the full stacktrace and the SDK API that encounters it?

**Comment by Star-Lord-MSA** [comment]
Hi,
Sorry this issue was also addressed in your support system and now we are waiting for the new release.
